name: Validate Codeowners
on:
  workflow_dispatch:

  pull_request:

permissions:
  contents: read

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

        # Leave pinned at 0.7.1 until https://github.com/mszostok/codeowners-validator/issues/173 is resolved
      - uses: mszostok/codeowners-validator@2f478ec3b2c8a321d46fca773f6285a447234f6a # v0.7.1
        if: github.event.pull_request.head.repo.full_name == github.repository
        name: "Full check of CODEOWNERS"
        with:
          # For now, remove "files" check to allow CODEOWNERS to specify non-existent
          # files so we can use the same CODEOWNERS file for Terraform and non-Terraform repos
          #   checks: "files,syntax,owners,duppatterns"
          checks: "syntax,owners,duppatterns"
          owner_checker_allow_unowned_patterns: "false"
          # GitHub access token is required only if the `owners` check is enabled
          github_access_token: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
      - uses: mszostok/codeowners-validator@2f478ec3b2c8a321d46fca773f6285a447234f6a # v0.7.1
        if: github.event.pull_request.head.repo.full_name != github.repository
        name: "Syntax check of CODEOWNERS"
        with:
          checks: "syntax,duppatterns"
          owner_checker_allow_unowned_patterns: "false"
